<?php

declare(strict_types=1);

return [
    'site' => [
        'phone' => '33 37 35 20 50',
        'email' => 'contacto@wiznet.mx',
        'address' => '16 de septiembre #117 Loc. Corralillos Mpio. Zapotlanejo Jalisco.',
        'map_embed' => 'https://www.google.com/maps?q=16%20de%20septiembre%20117%20Corralillos%20Jalisco&z=15&output=embed',
        'copyright' => '© Copyright 2025 WIZNET - Todos los derechos reservados.',
    ],
    'offices' => [
        'OFICINA CORRALILLOS',
    ],
    'featured_residential_packages' => [
        [
            'slug' => 'basico-residencial',
            'name' => 'PAQ. BASICO RESIDENCIAL',
            'description' => 'Paquete ideal para consumos bajos que requieren mensajeria y tareas de baja demanda.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 5MB de Descarga x 2MB de Carga durante 1 mes.',
            'price' => '$17',
            'price_note' => 'Costo Mensual',
        ],
        [
            'slug' => 'medio-residencial',
            'name' => 'PAQ. MEDIO RESIDENCIAL',
            'description' => 'Paquete ideal para consumos medios que requieren mensajeria y entretenimiento.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 7MB de Descarga x 3MB de Carga durante 1 mes.',
            'price' => '$23',
            'price_note' => 'Costo Mensual',
        ],
        [
            'slug' => 'alto-residencial',
            'name' => 'PAQ. ALTO RESIDENCIAL',
            'description' => 'Paquete ideal para consumos altos que requieren mensajeria, descargas y entretenimiento.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 10MB de Descarga x 5MB de Carga durante 1 mes.',
            'price' => '$33',
            'price_note' => 'Costo Mensual',
        ],
    ],
    'commercial_packages' => [
        [
            'slug' => 'basico-comercial',
            'name' => 'PAQ. BASICO COMERCIAL',
            'description' => 'Paquete ideal para consumos bajos que requieren mensajeria y tareas de baja demanda.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 15MB de Descarga x 15MB de Carga durante 1 mes.',
            'price' => '$80',
            'price_note' => 'Costo Mensual',
        ],
        [
            'slug' => 'medio-comercial',
            'name' => 'PAQ. MEDIO COMERCIAL',
            'description' => 'Paquete ideal para consumos medios que requieren mensajeria y entretenimiento.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 30MB de Descarga x 30MB de Carga durante 1 mes.',
            'price' => '$134',
            'price_note' => 'Costo Mensual',
        ],
        [
            'slug' => 'alto-comercial',
            'name' => 'PAQ. ALTO COMERCIAL',
            'description' => 'Paquete ideal para consumos altos que requieren mensajeria, descargas y entretenimiento.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 50MB de Descarga x 50MB de Carga durante 1 mes.',
            'price' => '$188',
            'price_note' => 'Costo Mensual',
        ],
    ],
    'residential_packages' => [
        [
            'slug' => 'paq-basico-residencial',
            'name' => 'PAQ. BASICO RESIDENCIAL',
            'description' => 'Paquete ideal para consumos bajos que requieren mensajeria y tareas de baja demanda.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 5MB de Descarga x 2MB de Carga durante 1 mes.',
            'price' => '$19',
            'price_note' => 'Costo Mensual',
            'speed' => '5MB / 2MB',
        ],
        [
            'slug' => 'paq-medio-residencial',
            'name' => 'PAQ. MEDIO RESIDENCIAL',
            'description' => 'Paquete ideal para consumos medios que requieren mensajeria y entrenamiento.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 7MB de Descarga x 3MB de Carga durante 1 mes.',
            'price' => '$26',
            'price_note' => 'Costo Mensual',
            'speed' => '7MB / 3MB',
        ],
        [
            'slug' => 'paq-alto-residencial',
            'name' => 'PAQ. ALTO RESIDENCIAL',
            'description' => 'Paquete ideal para consumos altos que requieren mensajeria, descargas y entretenimiento.',
            'details' => 'Este paquete le ofrece una navegacion ilimitada con 10MB de Descarga x 5MB de Carga durante 1 mes.',
            'price' => '$36',
            'price_note' => 'Costo Mensual',
            'speed' => '10MB / 5MB',
        ],
    ],
    'coverage' => [
        [
            'city' => 'Zapotlanejo',
            'zones' => [
                'Zapotlanejo',
                'La Laja',
                'La Mezquitera',
                'La Mora',
                'Santa Maria (tacuache)',
                'La Yerbabuena',
                'El Canuto',
                'Agua Escondida',
                'Cuchillas',
                'La Paz',
                'Corralillos',
                'El Saucillo',
                'Buenos Aires',
                'El Cerrito',
                'El Salto (coyotes)',
            ],
        ],
        [
            'city' => 'Juanacatlan',
            'zones' => [
                'San Isidro',
                'Miraflores',
                'Exhacienda',
                'Juanacatlan',
                'San Antonio',
                'Casa de Teja',
                'Villas Andalucia',
                'Estancia de Guadalupe',
            ],
        ],
        [
            'city' => 'El Salto',
            'zones' => [
                'El Muey',
                'El Salto',
                'Las Lilas',
                'El Pedregal',
                'La Azucena',
                'Sima serena',
                'Los Laureles',
                'Potrero Nuevo',
            ],
        ],
        [
            'city' => 'Tonala',
            'zones' => [
                'Tololotan',
                'El calaboso',
                'Agua Blanca',
                'Puente Grande',
            ],
        ],
    ],
    'support_tips' => [
        [
            'slug' => 'fallas-servicio',
            'title' => '¿Tienes Fallas en tu servicio?',
            'message' => 'Por favor desconecte sus equipos de la electricidad por un par de minutos y vuelva a conectarlos para refrescar su conexion a Internet.',
            'icon' => 'wrench',
        ],
        [
            'slug' => 'led-apagada',
            'title' => '¿Tienes alguna luz LED apagada en alguno de tus equipos?',
            'message' => 'Por favor revisa que tus equipos se encuentren conectados a la energia o que la terminal cuente con el suministro de energia.',
            'icon' => 'bulb',
        ],
        [
            'slug' => 'cables-red',
            'title' => '¿Tienes alguna duda de como van los cables de red?',
            'message' => 'Si realizaste algun cambio de lugar o desconectaste tus equipos de red y no sabes como conectarlos de nuevo por favor comunicate con nosotros para ayudarte.',
            'icon' => 'question',
        ],
        [
            'slug' => 'luces-led',
            'title' => '¿Ya no encienden las luces LED de mi equipo(s)?',
            'message' => 'Si ya realizaste las pruebas de los pasos 1,2 y 3 pero no logras tener servicio por favor comunicate con soporte para brindarte el apoyo necesario.',
            'icon' => 'idea',
        ],
    ],
    'faqs' => [
        '¿Consultar su numero de cliente?',
        '¿Donde puede pagar su servicio?',
        '¿Puedo cambiar de paquete?',
        '¿Puedo suspender o cancelar mi servicio?',
        '¿Puedo restablecer los ajustes de mis equipos?',
        '¿Si requiero soporte o una visita tiene algun costo?',
    ],
    'footer_services' => [
        ['label' => 'Internet Residencial', 'page' => 'internet-residencial'],
        ['label' => 'Contratar Servicio', 'page' => 'contratar-servicio'],
        ['label' => 'Realizar Pago en Linea', 'page' => 'registro-pagos'],
    ],
    'footer_links' => [
        'Registro Tarifas IFT' => '#',
        'Aviso de Privacidad' => '#',
        'Carta de Derechos Minimos' => '#',
        'Registro de Concesion' => '#',
        'Registro de Profeco' => '#',
        'Politica de Gestion de Trafico' => '#',
    ],
];
